### ISSUE TITLE
Get file from Sharepoint

### ISSUE THREAD

**Issue by isawek** [OfficeDev/Office-Add-in-NodeJS-SSO#18]
I use this for a Word Add-in and getting Data from graph works fine. But i also try to get a file from SharePoint but get an Unauthorized because the Token is valid for Graph and not for my SharePoint site.

do you have a tipp or idea, how i get the right Token for Sharepoint? i tried to get the token with auth.acquireTokenOnBehalfOf(jwt, ['Files.Read.All'], 'myTenant.sharepoint.com'); but it doesnt work.

Thank you
Dominik

@Rick-Kirkham @ardabeyazoglu

**Comment by ardabeyazoglu** [comment]
I never used sharepoint, so i am not sure how its done, however i have some ideas. First of all, in which domain are you trying to use office addin? Local office installation, office365.com ?

EDIT: Also, please share which graph api endpoints you use and what type of errors you are getting ?

**Comment by Rick-Kirkham** [comment]
This page seems to say that you can get SharePoint data using Microsoft Graph: https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/sharepoint

But I don't think you should pass a third (resource) parameter to auth.acquireTokenOnBehalfOf because the token issuer is AAD v. 2.0. The 2.0 endpoint does not take a resource parameter. It infers the resource from the scopes that you request. 
I'm not sure that Files.Read.All is going to be enough. You might need Sites.Read.All and/or Directory.Read.All.
