### ISSUE TITLE
getAccessTokenAsync - Token lacks signature part and can't be decoded

### ISSUE THREAD

**Issue by cbuettemeier** [OfficeDev/Office-Add-in-NodeJS-SSO#22]
I'm creating an outlook add-in, and trying to create SSO access. I am getting the app-token, via office.context.auth.getaccesstokenasync and pushing it to a expressjs middleware component, just like in this example here in the repository. Decoding in the auth.ts fails. After having a look at the token itself, it seems invalid as it is one ,-section short.

It works flawlessly in our own tenant (using Addin in Outlook on Win 10):
![screenshot_1](https://user-images.githubusercontent.com/29104197/48104096-4d6c8580-e232-11e8-94fb-ea9e37855454.png)

The token is incomplete in our customers tenant with the same configuration:
![screenshot_2](https://user-images.githubusercontent.com/29104197/48104133-6bd28100-e232-11e8-8c69-e8d5a15bd719.png)

Any hint where to look here?

**Comment by Rick-Kirkham** [comment]
@cbuettemeier The issues in this repo are used to track problems with this sample. Since you are now working with your own add-in, it would be better to raise this issue on StackOverflow so that more knowledgeable people will see it and the whole community will benefit from the answers that you get. Be sure to tag the question `office-js`.

**Comment by cbuettemeier** [comment]
Jep, you are right. Since my addin is build on this example, I thought there might be something I have overlooked here, I can't do much more than calling Office.context.auth.getAccessTokenAsync and work with what I am getting (which works in one tenant).

Sorry for hijacking here.
